import './search-room.scss'
import '../../components/header/header'
import '../../components/__filter-date-dropdown/filter-date-dropdown'
import '../../components/__dropdown/dropdown'
import '../../components/__range-slider/range-slider'
import '../../components/__dropdown-bedroom/dropdown-bedroom'
import '../../components/__expandable-checkbox-list/expandabel-checkbox-list'
import '../../components/hotel-room/hotel-room'
